backend:
  image:
    repository: noor2205/paytrack-backend
    tag: a2fd603

frontend:
  image:
    repository: noor2205/paytrack-frontend
    tag: a2fd603

mysql:
  image: mysql:8.3
  rootPassword: 22639646410Aa
  database: PayTrackDB
  user: root

ingress:
  enabled: true
  host: paytrack-helm.local

  backendPaths:
    - path: /employees
    - path: /hrs
    - path: /admins
    - path: /managers
    - path: /users
    - path: /leaves
    - path: /department
