apiVersion: v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: paytrack
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: paytrack-backend
    template:
      metadata:
        labels:
          app: paytrack-backend
      spec:
        containers:
          - name: paytrack-backend
            image: <usernameof dockerhub>/imahename
            ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: paytrack
spec: 
  selector:
    app: paytrack-backend
  ports:
    - port: 8080
      targetPort: 8080