apiVersion: apps/v1  
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: paytrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.3
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paytrack-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: PayTrackDB
          volumeMounts:
            - name: initdb
              # mountPath: /var/lib/mysql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb
          configMap:
            name: mysql-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-pvc
  namespace: paytrack
spec:
  type: ClusterIP
  selector:
    app: mysql
  
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
