apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: paytrack-backend
  ports:
    - port: 8080
      targetPort: 8080
