apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: paytrack-frontend
  ports:
    - port: 80
      targetPort: 80
