apiVersion: apps/v1
kind: Deployment
metadata:
  name: paytrack-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paytrack-frontend
  template:
    metadata:
      labels:
        app: paytrack-frontend
    spec:
      containers:
        - name: paytrack-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
