{% comment %} apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: mysql-init
          image: mysql:8.3
          command: ["/bin/sh", "-c"]
          args:
            - |
              for f in /init-sql/*.sql; do
                echo "Running $f";
                mysql -h mysql -u root -p{{ .Values.mysql.rootPassword }} {{ .Values.mysql.database }} < "$f";
              done
          volumeMounts:
            - name: init-sql
              mountPath: /init-sql
      restartPolicy: OnFailure
      volumes:
        - name: init-sql
          configMap:
            name: mysql-sql-bundle {% endcomment %}
