name: CI/CD Pipeline #name of the github actions workflow
#trigger commands: run when a commit is pushed on main branch 
on:
  push:
    branches:
      - main  # Run this when code is pushed to the main branch

jobs:
  build-and-deploy: #job name
    runs-on: ubuntu-latest #runs on ubuntu latest
    # puls the code form the repo into the runner so github actions can access it 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    #Sets up Docker Buildx, an extended build tool 
    #for Docker that supports multi-platform builds and caching.
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    #login to docker hub using github secrets 
    #used so that docker images can be pushed to docker hub 
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    #build and push docker image
    - name: Build and Push Backend Image
      run: |
        docker build -t noor2205/paytrack-backend -f docker/Dockerfile.backend .
        docker push noor2205/paytrack-backend

    - name: Build and Push Frontend Image
      run: |
        docker build -t noor2205/paytrack-frontend -f docker/Dockerfile.frontend .
        docker push noor2205/paytrack-frontend
    #kubeconfig: tells whcih cluster to connect to and what namespace or context to use
    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
    #deploy to kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8/namespace.yaml
        kubectl apply -f k8/secrets.yaml
        kubectl apply -f k8/configmap.yaml
        kubectl apply -f k8/mysql-initdb-config.yaml
        kubectl apply -f k8/mysql-deployment.yaml
        kubectl apply -f k8/frontend-deployment.yaml
        kubectl apply -f k8/backend-deployment.yaml
        kubectl apply -f k8/ingress.yaml
