name: PayTrack CI/CD

on:
  push:
    branches:
      - main
      - CICD-argoCD
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'charts/paytrack/**'

jobs:
  build-and-deploy:
    name: Build Docker Images & Trigger ArgoCD
    runs-on: self-hosted

    env:
      BACKEND_IMAGE: noor2205/paytrack-backend
      FRONTEND_IMAGE: noor2205/paytrack-frontend
      CHART_PATH: charts/paytrack

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Short Commit ID
        run: echo "COMMIT_ID=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend Image
        run: |
          docker build -t $BACKEND_IMAGE:${{ env.COMMIT_ID }} -f docker/Dockerfile.backend .
          docker push $BACKEND_IMAGE:${{ env.COMMIT_ID }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t $FRONTEND_IMAGE:${{ env.COMMIT_ID }} -f docker/Dockerfile.frontend .
          docker push $FRONTEND_IMAGE:${{ env.COMMIT_ID }}

      - name: Update values.yaml with new tag
        run: |
          sed -i "s/tag: .*/tag: ${{ env.COMMIT_ID }}/" $CHART_PATH/values.yaml

      - name: Commit updated values.yaml
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update image tag to ${{ env.COMMIT_ID }}"
          add: "${{ env.CHART_PATH }}/values.yaml"

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd && sudo mv argocd /usr/local/bin/argocd

      - name: Trigger ArgoCD Sync
        run: |
          argocd login paytrack-helm.local --insecure --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --grpc-web
          argocd app sync paytrack --prune
